import type { Metadata } from "next";
import { Inter, Jost, Schibsted_Grotesk } from "next/font/google";
import localfont from "next/font/local"
import Footer from "@/components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"],
  variable:"--font-inter",

 });
const jost = Jost({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jost",
  weight: "400"
})

const schgrotesk = Schibsted_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-schgrotesk",
  weight: "600"
})

const grotesk = localfont({
  src: [{
    path: '../public/fonts/SharpGrotesk-SemiBold10.otf',
    weight: "500"
  }],
  variable: '--font-grotesk'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${jost.variable} ${grotesk.variable} ${schgrotesk.variable}`}>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
